### ISSUE TITLE
Brodsky - Admin Ticket System

### ISSUE THREAD

**Issue by BrettMayson** [SynixeContractors/Crate#39]
We used to have a bot for this, maybe we could do it with Brodsky?

**Comment by mp-singh** [comment]
Needs more information.

**Comment by matidp4** [comment]
Basically when we do an "intervention" with a member, there used to be a tool that would hop on the channel, keep track of everything that was talked about and save it. It would then post it on a channel called transcripts to keep a record of incidents

**Comment by BrettMayson** [comment]
I don't think there is enough of a need for this for us to ever actually make it, closing for now
